### ISSUE TITLE
symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by j-f1** [swiftwasm/swift#1363] opened 2020-07-03 15:42 UTC
With the Tokamak demo, a clean `.build/wasm32-unknown-wasi` directory, and .swift-version specified as `wasm-DEVELOPMENT-SNAPSHOT-2020-07-02-a`, I get this error:

```shellsession
$ carton dev --product TokamakDemo
Polyfill integrity verified: /Users/jed/.carton/static/dev.js
Inferring basic settings...
- swift executable: /Users/jed/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-07-02-a/usr/bin/swift
Swift version 5.3-dev (LLVM c5b1848323200a8, Swift 66efa1272c2973b)
Target: x86_64-apple-darwin19.5.0
Parsing package manifest: /Users/jed/.carton/sdk/wasm-DEVELOPMENT-SNAPSHOT-2020-07-02-a/usr/bin/swift package dump-package
Error: Process failed with non-zero exit status and following error output:
/Users/jed/Documents/github-clones/Forks/Tokamak: error: manifest parse error(s):
Undefined symbols for architecture x86_64:
  "_$s18PackageDescription17SupportedPlatformV12MacOSVersionV6v10_15AEvau", referenced from:
      _main in Package-98b7ab.o
ld: symbol(s) not found for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
```

**Comment by MaxDesiatov** [comment] 2020-07-03 22:21
I think this is one is an issues caused by the `.build` directory left over from a previous snapshot being inconsistent with what SwiftPM from the new snapshot expects. I think if you remove '.build` and rebuild you'll either get #1365 or #1362.

**Comment by MaxDesiatov** [comment] 2020-07-08 13:50
I think the issue is resolved in `wasm-DEVELOPMENT-SNAPSHOT-2020-07-07-a`, feel free to reopen otherwise.

**Closed by MaxDesiatov** 2020-07-08 13:50 UTC

**Comment by j-f1** [comment] 2020-07-08 15:27
I can’t confirm either way because I haven’t been able to reproduce it for a bit but I couldn’t reproduce it in this version either

**Comment by MaxDesiatov** [comment] 2020-07-08 15:28
Cool, no worries. 👍
