### ISSUE TITLE
Compiled module was created by a newer version of the compiler

### ISSUE THREAD

**Issue by j-f1** [swiftwasm/swift#1362] opened 2020-07-03 15:39 UTC
With the Tokamak demo, a clean `.build/wasm32-unknown-wasi` directory, and `.swift-version` specified as `wasm-5.3-SNAPSHOT-2020-07-02-a`, I get this error:

```shellsession
$ carton dev --product TokamakDemo
Polyfill integrity verified: /Users/jed/.carton/static/dev.js
Inferring basic settings...
- swift executable: /Users/jed/.carton/sdk/wasm-5.3-SNAPSHOT-2020-07-02-a/usr/bin/swift
Swift version 5.3-dev (LLVM 52273b3a73, Swift a970a7362c)
Target: x86_64-apple-darwin19.5.0
Parsing package manifest: /Users/jed/.carton/sdk/wasm-5.3-SNAPSHOT-2020-07-02-a/usr/bin/swift package dump-package
Error: Process failed with non-zero exit status and following error output:
/Users/jed/Documents/github-clones/Forks/Tokamak: error: manifest parse error(s):
<unknown>:0: error: compiled module was created by a newer version of the compiler: /Users/jed/.carton/sdk/wasm-5.3-SNAPSHOT-2020-07-02-a/usr/lib/swift/macosx/Swift.swiftmodule/x86_64-apple-macos.swiftmodule
```

**Comment by MaxDesiatov** [comment] 2020-07-03 16:50
I hope that the issues is fixed https://github.com/swiftwasm/swift/commit/c7557be7a5ed9dda99e2262b509939dd90a643ce, if the build passes, it would be tagged as tonight's 5.3 snapshots. Let's wait and see.

**Comment by MaxDesiatov** [comment] 2020-07-03 22:16
I think this exact issue will be fixed in tonight's snapshot, at least not able to reproduce it locally anymore thanks to c7557be. Nevertheless, there's a different issue with SwiftPM on macOS, which prevents it from working properly. I think it has something to be with how `libPackageDescription.dylib`that belongs to SwiftPM is compiled. If you completely clean your `.build` directory (for any package, not just Tokamak) you get this error: 
```
 error: manifest parse error(s):
<unknown>
```

The breakage happens when the `Package.swift` manifest path is compiled, you can infer by passing the `-v` flag to `swift build` and checking where exactly the error occurs:

```
/Users/maxd/.swiftenv/versions/wasm-DEVELOPMENT-SNAPSHOT-2020-06-13-a/usr/bin/swiftc -L /Users/maxd/.swiftenv/versions/wasm-DEVELOPMENT-SNAPSHOT-2020-06-13-a/usr/lib/swift/pm/4_2 -lPackageDescription -Xlinker -rpath -Xlinker /Users/maxd/.swiftenv/versions/wasm-DEVELOPMENT-SNAPSHOT-2020-06-13-a/usr/lib/swift/pm/4_2 -target x86_64-apple-macosx10.15 -swift-version 5 -I /Users/maxd/.swiftenv/versions/wasm-DEVELOPMENT-SNAPSHOT-2020-06-13-a/usr/lib/swift/pm/4_2 -sdk /Applications/Xcode-11.5.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -package-description-version 5.2.0 /Users/maxd/Documents/Tokamak/Package.swift -o /var/folders/r4/5d00qxmn0rz1v00hb9lv3fdr0000gn/T/TemporaryDirectory.MvuBHz/tokamak-manifest
/var/folders/r4/5d00qxmn0rz1v00hb9lv3fdr0000gn/T/TemporaryDirectory.MvuBHz/tokamak-manifest -fileno 7 sandbox-exec -p '(version 1)
(deny default)
(import "system.sb")
(allow file-read*)
(allow process*)
(allow sysctl*)
(allow file-write*
    (regex #"^/private/var/tmp/org\.llvm\.clang.*")
    (regex #"^/var/folders/r4/5d00qxmn0rz1v00hb9lv3fdr0000gn/T/org\.llvm\.clang.*")
    (regex #"^/private/var/folders/r4/5d00qxmn0rz1v00hb9lv3fdr0000gn/T/org\.llvm\.clang.*")
    (regex #"^/private/var/folders/r4/5d00qxmn0rz1v00hb9lv3fdr0000gn/C/org\.llvm\.clang.*")
    (subpath "/Users/maxd/Documents/Tokamak/.build")
)
'
/Users/maxd/Documents/Tokamak: error: manifest parse error(s):
<unknown>
``` 

Note that I'm using `2020-06-13-a` snapshot in the above output, that's the oldest snapshot where the issue is reproduced. `2020-06-12-a` snapshot is working fine. I've also tried to compile the manifest file separately by `2020-06-13-a` and `2020-06-12-a` versions of the compiler, but using the same version of the `libPackageDescription.dylib` module from either `2020-06-13-a` or `2020-06-12-a`. Testing these different combinations, I think that the issues is caused by `libPackageDescription.dylib` that became broken in `2020-06-13-a` and is still broken in the latest snapshots for both `swiftwasm-release/5.3` and `swiftwasm` branches. Looking at file sizes, we can also see that something happened to the library that significantly changed its binary size starting with the `2020-06-13-a` snapshot:

```
892K	/Users/maxd/.swiftenv/versions/wasm-DEVELOPMENT-SNAPSHOT-2020-06-11-a/usr/lib/swift/pm/4_2/libPackageDescription.dylib
892K	/Users/maxd/.swiftenv/versions/wasm-DEVELOPMENT-SNAPSHOT-2020-06-12-a/usr/lib/swift/pm/4_2/libPackageDescription.dylib
752K	/Users/maxd/.swiftenv/versions/wasm-DEVELOPMENT-SNAPSHOT-2020-06-13-a/usr/lib/swift/pm/4_2/libPackageDescription.dylib
756K	/Users/maxd/.swiftenv/versions/swift-wasm-5.3-SNAPSHOT-2020-07-03-a/usr/lib/swift/pm/4_2/libPackageDescription.dylib
752K	/Users/maxd/.swiftenv/versions/wasm-DEVELOPMENT-SNAPSHOT-2020-06-22-a/usr/lib/swift/pm/4_2/libPackageDescription.dylib
```

There don't seem to be any changes between `2020-06-12-a` and `2020-06-13-a` in the SwiftPM itself, I think something changed in the compiler that made it miscompile the library. 

I'm going to research this further, need to investigate what exactly is different between those two compiler versions and how to fix it.

**Comment by MaxDesiatov** [comment] 2021-09-02 21:25
Haven't seen this reproduced in long time, closing as outdated.

**Closed by MaxDesiatov** 2021-09-02 21:25 UTC
Labels: bug
